package Controller;

import View.APayrollSearchView;
import View.APayrollReport;
import View.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;

/**
 * The controller class for managing the interactions between the APayrollSearchView and APayrollReport.
 */
public class APayrollSearchController {
    private APayrollSearchView view;

    /**
     * Constructs an instance of the APayrollSearchController.
     *
     * @param view The APayrollSearchView instance to control.
     */
    public APayrollSearchController(APayrollSearchView view) {
        this.view = view;

        view.addSubmitButtonListener(new ActionListener() {
            /**
             * Handles the actionPerformed event for the submit button.
             *
             * @param e The ActionEvent generated by the submit button click.
             */
            public void actionPerformed(ActionEvent e) {
                
                String startYear = view.getStartYear();
                String startMonth = view.getStartMonth();
                String startDay = view.getStartDay();
                String startDateString = startYear + "-" + startMonth + "-" + startDay;
                String endYear = view.getEndYear();
                String endMonth = view.getEndMonth();
                String endDay = view.getEndDay();
                String endDateString = endYear + "-" + endMonth + "-" + endDay;

                // Create and display the APayrollReport view with the selected date range
                APayrollReport reportView = new APayrollReport(startDateString, endDateString);
            }
        });

        view.addCancelButtonListener(new ActionListener() {
            /**
             * Handles the actionPerformed event for the cancel button.
             *
             * @param e The ActionEvent generated by the cancel button click.
             */
            public void actionPerformed(ActionEvent e) {
                // Close the APayrollSearchView when the cancel button is clicked
                view.dispose();
            }
        });
    }

    /**
     * The main method to start the APayrollSearchController.
     *
     * @param args The command-line arguments (not used in this context).
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            /**
             * Runs the APayrollSearchController by creating an instance with a new APayrollSearchView.
             */
            public void run() {
                new APayrollSearchController(new APayrollSearchView());
            }
        });
    }
}
